
package com.qf.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MyPhoneImplService", targetNamespace = "http://webservice.qf.com/", wsdlLocation = "http://localhost:8080/myphone?wsdl")
public class MyPhoneImplService
    extends Service
{

    private final static URL MYPHONEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MYPHONEIMPLSERVICE_EXCEPTION;
    private final static QName MYPHONEIMPLSERVICE_QNAME = new QName("http://webservice.qf.com/", "MyPhoneImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/myphone?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MYPHONEIMPLSERVICE_WSDL_LOCATION = url;
        MYPHONEIMPLSERVICE_EXCEPTION = e;
    }

    public MyPhoneImplService() {
        super(__getWsdlLocation(), MYPHONEIMPLSERVICE_QNAME);
    }

    public MyPhoneImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MYPHONEIMPLSERVICE_QNAME, features);
    }

    public MyPhoneImplService(URL wsdlLocation) {
        super(wsdlLocation, MYPHONEIMPLSERVICE_QNAME);
    }

    public MyPhoneImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MYPHONEIMPLSERVICE_QNAME, features);
    }

    public MyPhoneImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyPhoneImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MyPhoneImpl
     */
    @WebEndpoint(name = "MyPhoneImplPort")
    public MyPhoneImpl getMyPhoneImplPort() {
        return super.getPort(new QName("http://webservice.qf.com/", "MyPhoneImplPort"), MyPhoneImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyPhoneImpl
     */
    @WebEndpoint(name = "MyPhoneImplPort")
    public MyPhoneImpl getMyPhoneImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.qf.com/", "MyPhoneImplPort"), MyPhoneImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MYPHONEIMPLSERVICE_EXCEPTION!= null) {
            throw MYPHONEIMPLSERVICE_EXCEPTION;
        }
        return MYPHONEIMPLSERVICE_WSDL_LOCATION;
    }

}
