
package com.qf.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MyPhoneImpl", targetNamespace = "http://webservice.qf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MyPhoneImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryPhone", targetNamespace = "http://webservice.qf.com/", className = "com.qf.webservice.QueryPhone")
    @ResponseWrapper(localName = "queryPhoneResponse", targetNamespace = "http://webservice.qf.com/", className = "com.qf.webservice.QueryPhoneResponse")
    @Action(input = "http://webservice.qf.com/MyPhoneImpl/queryPhoneRequest", output = "http://webservice.qf.com/MyPhoneImpl/queryPhoneResponse")
    public String queryPhone(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
